import XLSX from 'xlsx';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLACEHOLDER_CYCLE = ['placeholderCircle', 'placeholderTriangle', 'placeholderSquare', 'placeholderHeart'];
const CATEGORY_KEY = { '초성': 'cho', '쌍자음': 'cho', '중성': 'jung', '이중모음': 'jung', '숫자': 'digit', '특수문자': 'special' };

function parseMarkToken(token) {
  // "line:right:1" -> {mark:'line', position:'right', count:1}
  // "dot:right"    -> {mark:'dot', positions:['right']}
  // "dot:right,bottom" -> {mark:'dot', positions:['right','bottom']}
  // "pin:right"    -> {mark:'pin', position:'right'}
  const [mark, posPart, countPart] = token.split(':');
  if (mark === 'dot') {
    return { mark: 'dot', positions: posPart.split(',') };
  }
  if (mark === 'pin') {
    return { mark: 'pin', position: posPart };
  }
  return { mark: 'line', position: posPart, count: Number(countPart) };
}

function parseRecipe(category, raw) {
  if (category === '중성' || category === '이중모음') {
    if (raw.startsWith('combo:')) {
      const marksPart = raw.slice('combo:'.length);
      const marks = marksPart.split('+').map(parseMarkToken);
      return { mark: 'combo', marks };
    }
    if (raw.startsWith('pinMidDouble:')) return { mark: 'pinMidDouble', position: raw.split(':')[1] };
    if (raw.startsWith('pinEndDouble:')) return { mark: 'pinEndDouble', position: raw.split(':')[1] };
    if (raw.startsWith('pinMid:')) return { mark: 'pinMid', position: raw.split(':')[1] };
    if (raw.startsWith('pinEnd:')) return { mark: 'pinEnd', position: raw.split(':')[1] };
    return parseMarkToken(raw);
  }

  // cho / digit / special: "shape[:count][+modifier]"
  const [shapePart, modifier] = raw.split('+');
  const [shape, count] = shapePart.split(':');
  const recipe = { shape };
  if (count !== undefined) recipe.count = Number(count);
  if (modifier) recipe.modifier = modifier;
  return recipe;
}

export function buildSymbolMap(rows) {
  const map = { cho: {}, jung: {}, digit: {}, special: {} };
  const placeholderIndex = { cho: 0, jung: 0, digit: 0, special: 0 };

  for (const row of rows.slice(1)) {
    const [category, jamo, rawSymbol] = row;
    if (!category || !jamo) continue;
    const bucketKey = CATEGORY_KEY[category];
    if (!bucketKey) continue;

    const raw = (rawSymbol || '').trim();
    if (raw === '') {
      const shape = PLACEHOLDER_CYCLE[placeholderIndex[bucketKey] % PLACEHOLDER_CYCLE.length];
      placeholderIndex[bucketKey] += 1;
      map[bucketKey][jamo] = { shape };
      continue;
    }
    map[bucketKey][jamo] = parseRecipe(category, raw);
  }
  return map;
}

export function generateSymbolMapFile(excelPath, outPath) {
  const wb = XLSX.readFile(excelPath);
  const sheet = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' });
  const map = buildSymbolMap(rows);
  const contents = `// AUTO-GENERATED by scripts/buildSymbols.js — do not hand-edit.\n// Regenerate with: npm run build-symbols\nexport const symbolMap = ${JSON.stringify(map, null, 2)};\n`;
  fs.writeFileSync(outPath, contents);
  return map;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const excelPath = path.join(__dirname, 'jamo-symbols.xlsx');
  const outPath = path.join(__dirname, '..', 'src', 'data', 'symbolMap.js');
  generateSymbolMapFile(excelPath, outPath);
  console.log(`Wrote ${outPath}`);
}
